# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 20:29
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='graphdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graphname', models.TextField()),
                ('graphid', models.TextField()),
                ('datestamp', models.DateField(auto_now_add=True)),
                ('timestamp', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='networkconn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('networkid', models.TextField()),
                ('LatLongId', models.BigIntegerField()),
                ('Lat', models.FloatField()),
                ('Long', models.FloatField()),
                ('LatLongx', models.FloatField(null=True)),
                ('LatLongy', models.FloatField(null=True)),
                ('ConnectedPoints', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='networkconnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('networkid', models.TextField()),
                ('LatLong', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('ConnectedPoints', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='nsrpt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
